// Extracted from https: //raw.githubusercontent.com/gilbarbara/logos/app/app/logos.json
module.exports = {
  '100tb': ['100tb.svg'],
  '500px': ['500px.svg'],
  '6px': ['6px.svg'],
  'AdRoll': ['adroll.svg'],
  'Aerospike': ['aerospike.svg'],
  'Airbnb': ['airbnb.svg'],
  'Airbrake': ['airbrake.svg'],
  'Akamai': ['akamai.svg'],
  'Alfresco': ['alfresco.svg'],
  'Algolia': ['algolia.svg'],
  'Ampersand.js': ['ampersand.svg'],
  'Android': ['android-icon.svg', 'android.svg'],
  'AngelList': ['angellist.svg'],
  'Angular': ['angular-icon.svg', 'angular.svg'],
  'Ansible': ['ansible.svg'],
  'Apache': ['apache.svg'],
  'Apache CloudStack': ['apache_cloudstack.svg'],
  'Apache Tomcat': ['tomcat.svg'],
  'api.ai': ['api-ai.svg'],
  'Apiary': ['apiary.svg'],
  'Apigee': ['apigee.svg'],
  'APItools': ['apitools.svg'],
  'Apollo': ['apollostack.svg'],
  'Appbase': ['appbase.svg'],
  'Appcelerator': ['appcelerator.svg'],
  'AppCode': ['appcode.svg'],
  'AppDynamics': ['appdynamics.svg'],
  'AppFog': ['appfog.svg'],
  'AppHub': ['apphub.svg'],
  'Appium': ['appium.svg'],
  'Apple': ['apple.svg'],
  'Appmaker': ['appmaker.svg'],
  'Apportable': ['apportable.svg'],
  'AppSignal': ['appsignal.svg'],
  'Apptentive': ['apptentive.svg'],
  'AppVeyor': ['appveyor.svg'],
  'ArangoDB': ['arangodb.svg'],
  'Arduino': ['arduino.svg'],
  'Asana': ['asana.svg'],
  'Atom': ['atom.svg'],
  'atomic': ['atomic.svg'],
  'Aurelia': ['aurelia.svg'],
  'Aurora': ['aurora.svg'],
  'Aurous': ['aurous.svg'],
  'Auth0': ['auth0.svg'],
  'Authy': ['authy.svg'],
  'autocode': ['autocode.svg'],
  'AutoIt': ['autoit.svg'],
  'Autoprefixer': ['autoprefixer.svg'],
  'Awesome': ['awesome.svg'],
  'AWS': ['aws.svg'],
  'AWS API Gateway': ['aws-api-gateway.svg'],
  'AWS CloudFormation': ['aws-cloudformation.svg'],
  'AWS CloudFront': ['aws-cloudfront.svg'],
  'AWS CloudSearch': ['aws-cloudsearch.svg'],
  'AWS CloudWatch': ['aws-cloudwatch.svg'],
  'AWS CodeDeploy': ['aws-codedeploy.svg'],
  'AWS Cognito': ['aws-cognito.svg'],
  'AWS DynamoDB': ['aws-dynamodb.svg'],
  'AWS EC2 (Elastic Compute Cloud)': ['aws-ec2.svg'],
  'AWS Glacier': ['aws-glacier.svg'],
  'AWS IAM (Identity and Access Management)': ['aws-iam.svg'],
  'AWS Lambda': ['aws-lambda.svg'],
  'AWS Mobile Hub': ['aws-mobilehub.svg'],
  'AWS Opworks': ['aws-opsworks.svg'],
  'AWS RDS (Relational Database Service)': ['aws-rds.svg'],
  'AWS Route 53': ['aws-route53.svg'],
  'AWS S3 (Simple Storage Service)': ['aws-s3.svg'],
  'AWS SES (Simple Email Service)': ['aws-ses.svg'],
  'AWS SNS (Simple Notification Service)': ['aws-sns.svg'],
  'AWS SQS (Simple Queue Service)': ['aws-sqs.svg'],
  'AWS WAF (Web Application Firewall)': ['aws-waf.svg'],
  'Babel': ['babel.svg'],
  'Backbone': ['backbone-icon.svg', 'backbone.svg'],
  'Baker Street': ['baker-street.svg'],
  'BackerKit': ['backerkit.svg'],
  'Base': ['base.svg'],
  'Basecamp': ['basecamp.svg'],
  'BaseKit': ['basekit.svg'],
  'batch': ['batch.svg'],
  'Bash': ['bash.svg'],
  'Bēhance': ['behance.svg'],
  'Bem': ['bem.svg'],
  'bigpanda': ['bigpanda.svg'],
  'Bing': ['bing.svg'],
  'BitBalloon': ['bitballoon.svg'],
  'Bitcoin': ['bitcoin.svg'],
  'Bitbucket': ['bitbucket.svg'],
  'Bitnami': ['bitnami.svg'],
  'Bitrise': ['bitrise.svg'],
  'Blocs': ['blocs.svg'],
  'Blogger': ['blogger.svg'],
  'Blossom': ['blossom.svg'],
  'Bluemix': ['bluemix.svg'],
  'Bluetooth': ['bluetooth.svg'],
  'Bootstrap': ['bootstrap.svg'],
  'Bosun': ['bosun.svg'],
  'bourbon': ['bourbon.svg'],
  'Bower': ['bower.svg'],
  'Bowtie': ['bowtie.svg'],
  'box': ['box.svg'],
  'Brackets': ['brackets.svg'],
  'Brandfolder': ['brandfolder.svg'],
  'Broccoli': ['broccoli.svg'],
  'Browserling': ['browserling.svg'],
  'Browserify': ['browserify-icon.svg', 'browserify.svg'],
  'BrowserStack': ['browserstack.svg'],
  'Browsersync': ['browsersync.svg'],
  'Brunch': ['brunch.svg'],
  'Buck': ['buck.svg'],
  'Buddy': ['buddy.svg'],
  'Buffer': ['buffer.svg'],
  'BugHerd': ['bugherd.svg'],
  'Bugsnag': ['bugsnag.svg'],
  'C': ['c.svg'],
  'C++': ['c++.svg'],
  'Cachet': ['cachet.svg'],
  'CakePHP': ['cakephp.svg'],
  'Campaign Monitor': ['campaignmonitor.svg'],
  'Campfire': ['campfire.svg'],
  'CanJS': ['canjs.svg'],
  'Capistrano': ['capistrano.svg'],
  'Cassandra': ['cassandra.svg'],
  'Celluloid': ['celluloid.svg'],
  'CentOS': ['centos-icon.svg', 'centos.svg'],
  'Chai': ['chai.svg'],
  'Chalk': ['chalk.svg'],
  'ChangeTip': ['changetip.svg'],
  'Chartblocks': ['chartblocks.svg'],
  'Chef': ['chef.svg'],
  'chevereto': ['chevereto.svg'],
  'Chrome': ['chrome.svg'],
  'CircleCI': ['circleci.svg'],
  'ClickDeploy': ['clickdeploy.svg'],
  'CLion': ['clion.svg'],
  'Clojure': ['clojure.svg'],
  'ClojureScript': ['cljs.svg'],
  'Close': ['close.svg'],
  'Cloud9': ['cloud9.svg'],
  'CloudAcademy': ['cloudacademy.svg'],
  'Cloudant': ['cloudant.svg'],
  'Cloudcraft': ['cloudcraft.svg'],
  'Cloudera': ['cloudera.svg'],
  'CloudFlare': ['cloudflare.svg'],
  'CloudLinux': ['cloudlinux.svg'],
  'ClusterHQ': ['clusterhq.svg'],
  'Cobalt': ['cobalt.svg'],
  'Cockpit': ['cockpit.svg'],
  'CocoaPods': ['cocoapods.svg'],
  'Code Climate': ['codeclimate.svg'],
  'Code School': ['codeschool.svg'],
  'Codebase': ['codebase.svg'],
  'codebeat': ['codebeat.svg'],
  'codecademy': ['codecademy.svg'],
  'Codeception': ['codeception.svg'],
  'Codecov': ['codecov.svg'],
  'CodeIgniter': ['codeigniter.svg'],
  'Codepen': ['codepen-icon.svg', 'codepen.svg'],
  'CodePush': ['codepush.svg'],
  'coderwall': ['coderwall.svg'],
  'Codeship': ['codeship.svg'],
  'Codio': ['codio.svg'],
  'Codrops': ['codrops.svg'],
  'CoffeeScript': ['coffeescript.svg'],
  'Compass': ['compass.svg'],
  'Component': ['component.svg'],
  'ComponentKit': ['componentkit.svg'],
  'Compose': ['compose.svg'],
  'Composer': ['composer.svg'],
  'Concourse': ['concourse.svg'],
  'concrete5': ['concrete5.svg'],
  'Consul': ['consul.svg'],
  'ContainerShip': ['containership.svg'],
  'Convox': ['convox.svg'],
  'Copyleft': ['copyleft.svg', 'copyleft-pirate.svg'],
  'Cordova': ['cordova.svg'],
  'CoreOS': ['coreos-icon.svg', 'coreos.svg'],
  'Couchbase': ['couchbase.svg'],
  'CouchDB': ['couchdb.svg'],
  'coursera': ['coursera.svg'],
  'Coveralls': ['coveralls.svg'],
  'Coverity': ['coverity.svg'],
  'cPanel': ['cpanel.svg'],
  'Craft': ['craft.svg'],
  'Crashlytics': ['crashlytics.svg'],
  'CrateIO': ['crateio.svg'],
  'CreateJS': ['createjs.svg'],
  'Crittercism': ['crittercism.svg'],
  'Cross Browser Testing': ['crossbrowsertesting.svg'],
  'CrowdProcess': ['crowdprocess.svg'],
  'Crystal': ['crystal.svg'],
  'CSS3': ['css-3.svg', 'css-3_official.svg'],
  'cssnext': ['cssnext.svg'],
  'Cucumber': ['cucumber.svg'],
  'Customer.io': ['customerio.svg'],
  'Cycle.js': ['cyclejs.svg'],
  'D3': ['d3.svg'],
  'dapulse': ['dapulse.svg'],
  'Dashlane': ['dashlane.svg'],
  'Dart': ['dart.svg'],
  'dat': ['dat.svg'],
  'Database Labs': ['database-labs.svg'],
  'debian': ['debian.svg'],
  'Delicious': ['delicious.svg'],
  'DeliciousDB': ['delicious-burger.svg'],
  'Delighted': ['delighted.svg'],
  'Dependency CI': ['dependencyci.svg'],
  'Deploy': ['deploy.svg'],
  'deppbot': ['deppbot.svg'],
  'Derby': ['derby.svg'],
  'Designer News': ['designernews.svg'],
  'Desk.com': ['desk.svg'],
  'DeviantArt': ['deviantart.svg'],
  'DigitalOcean': ['digitalocean.svg'],
  'Discord': ['discord.svg'],
  'Disqus': ['disqus.svg'],
  'distelli': ['distelli.svg'],
  'Divshot': ['divshot.svg'],
  'Django': ['django.svg'],
  'docker': ['docker.svg'],
  'Doctrine': ['doctrine.svg'],
  'Dojo Toolkit': ['dojo.svg'],
  'dotCloud': ['dotcloud.svg'],
  '.NET': ['dotnet.svg'],
  'DreamFactory': ['dreamfactory.svg'],
  'DreamHost': ['dreamhost.svg'],
  'dribbble': ['dribbble-icon.svg', 'dribbble.svg'],
  'Drip': ['drip.svg'],
  'Drone': ['drone.svg'],
  'Dropbox': ['dropbox.svg'],
  'dropmark': ['dropmark.svg'],
  'Dropzone': ['dropzone.svg'],
  'Drupal': ['drupal.svg'],
  'DuckDuckGo': ['duckduckgo.svg'],
  'Dyn': ['dyndns.svg'],
  'Eager': ['eager.svg'],
  'Eclipse': ['eclipse.svg'],
  'ElasticBox': ['elasticbox.svg'],
  'Elasticsearch': ['elasticsearch.svg'],
  'Electron': ['electron.svg'],
  'Elemental UI': ['elemental-ui.svg'],
  'elementary OS': ['elementary.svg'],
  'ello': ['ello.svg'],
  'elm': ['elm.svg'],
  'Emacs': ['emacs.svg'],
  'Embedly': ['embedly.svg'],
  'Ember': ['ember-tomster.svg', 'ember.svg'],
  'Emmet': ['emmet.svg'],
  'Engine Yard': ['engine-yard.svg'],
  'Envato': ['envato.svg'],
  'Envoyer': ['envoyer.svg'],
  'Enyo': ['enyo.svg'],
  'Erlang': ['erlang.svg'],
  'ES6': ['es6.svg'],
  'ESLint': ['eslint.svg'],
  'etcd': ['etcd.svg'],
  'Ethereum': ['ethereum.svg'],
  'Ethnio': ['ethnio.svg'],
  'EventSentry': ['eventsentry.svg'],
  'Exponent': ['exponent.svg'],
  'Express': ['express.svg'],
  'F#': ['fsharp.svg'],
  'Fabric': ['fabric.svg'],
  'Facebook': ['facebook.svg'],
  'Falcor': ['falcor.svg'],
  'Famo.us': ['famous.svg'],
  'Fastly': ['fastly.svg'],
  'feathersjs': ['feathersjs.svg'],
  'fedora': ['fedora.svg'],
  'Firebase': ['firebase.svg'],
  'Firefox': ['firefox.svg'],
  'flannel': ['flannel.svg'],
  'Flarum': ['flarum.svg'],
  'Flask': ['flask.svg'],
  'Flat UI': ['flat-ui.svg'],
  'Flattr': ['flattr.svg'],
  'Fleep': ['fleep.svg'],
  'flexible.gs': ['flexible-gs.svg'],
  'flickr': ['flickr-icon.svg', 'flickr.svg'],
  'Flight': ['flight.svg'],
  'Flocker': ['flocker.svg'],
  'Flood IO': ['floodio.svg'],
  'Flow': ['flow.svg'],
  'Flux': ['flux.svg'],
  'Fluxxor': ['fluxxor.svg'],
  'Fly': ['flyjs.svg'],
  'FlowXO': ['flowxo.svg'],
  'FormKeep': ['formkeep.svg'],
  'Forest': ['forest.svg'],
  'Forever': ['forever.svg'],
  'Foundation': ['foundation.svg'],
  'Framed': ['framed.svg'],
  'FreeBSD': ['freebsd.svg'],
  'freedcamp': ['freedcamp.svg'],
  'Free Cultural Works': ['freedomdefined.svg'],
  'Front': ['frontapp.svg'],
  'Gauge': ['gaugeio.svg'],
  'geekbot': ['geekbot.svg'],
  'Get Satisfaction': ['get-satisfaction.svg'],
  'Ghost': ['ghost.svg'],
  'Giant Swarm': ['giantswarm.svg'],
  'Git': ['git-icon.svg', 'git.svg'],
  'Gitboard': ['gitboard.svg'],
  'Github': ['github-icon.svg', 'github.svg', 'github-octocat.svg'],
  'GitKraken': ['gitkraken.svg'],
  'Gitlab': ['gitlab.svg'],
  'Gitter': ['gitter.svg'],
  'GitUp': ['gitup.svg'],
  'Gleam': ['gleam.svg'],
  'Glint': ['glint.svg'],
  'Go': ['gopher.svg'],
  'GoCD': ['gocd.svg'],
  'Google': ['google-icon.svg', 'google.svg', 'google-2014.svg'],
  'Google +': ['google-plus.svg'],
  'Google AdSense': ['google-adsense.svg'],
  'Google AdWords': ['google-adwords.svg'],
  'Google Analytics': ['google-analytics.svg'],
  'Google Cloud': ['google-cloud.svg'],
  'Google Developers': ['google-developers.svg'],
  'Google Drive': ['google-drive.svg'],
  'Google Gmail': ['google-gmail.svg'],
  'Google Photos': ['google-photos.svg'],
  'Gordon': ['gordon.svg'],
  'GNU': ['gnu.svg'],
  'Gradle': ['gradle.svg'],
  'Graphene': ['graphene.svg'],
  'GraphQL': ['graphql.svg'],
  'Grails': ['grails.svg'],
  'Grape': ['grape.svg'],
  'Gratipay': ['gratipay.svg'],
  'Grav': ['grav.svg'],
  'Gravatar': ['gravatar.svg'],
  'Graylog': ['graylog.svg'],
  'Groove': ['groovehq.svg'],
  'Grove': ['grove.svg'],
  'Grunt': ['grunt.svg'],
  'Gulp': ['gulp.svg'],
  'Gunicorn': ['gunicorn.svg'],
  'GWT': ['gwt.svg'],
  'hack': ['hack.svg'],
  'HackerOne': ['hacker-one.svg'],
  'Hadoop': ['hadoop.svg'],
  'Haml': ['haml.svg'],
  'Handlebars': ['handlebars.svg'],
  'hapi': ['hapi.svg'],
  'Harrow': ['harrow.svg'],
  'Hashnode': ['hashnode.svg'],
  'Haskell': ['haskell.svg'],
  'Haxe': ['haxe.svg'],
  'Haxl': ['haxl.svg'],
  'HBase': ['hbase.svg'],
  'Heap': ['heap.svg'],
  'Help Scout': ['helpscout.svg'],
  'Heroku': ['heroku.svg'],
  'Heroku Redis': ['heroku-redis.svg'],
  'Hexo': ['hexo.svg'],
  'Hibernate': ['hibernate.svg'],
  'HHVM': ['hhvm.svg'],
  'Highcharts': ['highcharts.svg'],
  'HipChat': ['hipchat.svg'],
  'Hoa': ['hoa.svg'],
  'Hoodie': ['hoodie.svg'],
  'Horizon': ['horizon.svg'],
  'HostGator': ['hostgator.svg'],
  'Hosted Graphite': ['hosted-graphite.svg'],
  'Hound': ['houndci.svg'],
  'HTML5': ['html-5.svg'],
  'HTML5 Boilerplate': ['html5-boilerplate.svg'],
  'Hubspot': ['hubspot.svg'],
  'Humongous': ['humongous.svg'],
  'HyperDev': ['hyperdev.svg'],
  'IEEE': ['ieee.svg'],
  'IFTTT': ['ifttt.svg'],
  'imagemin': ['imagemin.svg'],
  'Immutable': ['immutable.svg'],
  'Impala': ['impala.svg'],
  'import.io': ['importio.svg'],
  'Infer': ['infer.svg'],
  'InfluxDB': ['influxdb.svg'],
  'Ink': ['ink.svg'],
  'Instagram': ['instagram-icon.svg', 'instagram.svg'],
  'IntelliJ IDEA': ['intellij-idea.svg'],
  'Intercom': ['intercom.svg'],
  'Internet Explorer': ['internetexplorer.svg'],
  'Invision': ['invision.svg'],
  'io.js': ['io.svg'],
  'Ionic': ['ionic.svg'],
  'iOS': ['ios.svg'],
  'Iron.io': ['iron.svg'],
  'Jade': ['jade.svg'],
  'Jasmine': ['jasmine.svg'],
  'Java': ['java.svg'],
  'Javascript (JS)': ['javascript.svg'],
  'Jekyll': ['jekyll.svg'],
  'Jelastic': ['jelastic.svg'],
  'Jenkins': ['jenkins.svg'],
  'Jest': ['jest.svg'],
  'JetBrains': ['jetbrains.svg'],
  'Jhipster': ['jhipster.svg'],
  'JIRA': ['jira.svg'],
  'Joomla': ['joomla.svg'],
  'jQuery': ['jquery.svg'],
  'jQuery Mobile': ['jquery-mobile.svg'],
  'JRuby': ['jruby.svg'],
  'jsbin': ['jsbin.svg'],
  'JSCS': ['jscs.svg'],
  'jsDelivr': ['jsdelivr.svg'],
  'JSFiddle': ['jsfiddle.svg'],
  'JSON': ['json.svg'],
  'JSPM': ['jspm.svg'],
  'Juju': ['juju.svg'],
  'Kafka': ['kafka.svg'],
  'Kallithea': ['kallithea.svg'],
  'Karma': ['karma.svg'],
  'Keen IO': ['keen.svg'],
  'Keymetrics': ['keymetrics.svg'],
  'KeystoneJS': ['keystonejs.svg'],
  'Kemal': ['kemal.svg'],
  'Khan Academy': ['khan_academy.svg'],
  'Kickstarter': ['kickstarter.svg'],
  'Kinto': ['kinto.svg'],
  'Kinvey': ['kinvey.svg'],
  'kirby': ['kirby.svg'],
  'kissmetrics': ['kissmetrics.svg'],
  'Kitematic': ['kitematic.svg'],
  'Kloudless': ['kloudless.svg'],
  'Knex.js': ['knex.svg'],
  'Knockout': ['knockout.svg'],
  'Kong': ['kong.svg'],
  'Kontena': ['kontena.svg'],
  'Kore': ['koreio.svg'],
  'kore': ['kore.svg'],
  'Kotlin': ['kotlin.svg'],
  'Kraken': ['kraken.svg'],
  'Krakenjs': ['krakenjs.svg'],
  'Kubernetes': ['kubernets.svg'],
  'Laravel': ['laravel.svg'],
  'last.fm': ['lastfm.svg'],
  'Lateral': ['lateral.svg'],
  'LaunchKit': ['launchkit.svg'],
  'Launchrock': ['launchrock.svg'],
  'Leafjet': ['leafjet.svg'],
  'Leankit': ['leankit.svg'],
  'Less': ['less.svg'],
  'LevelDB': ['leveldb.svg'],
  'Librato': ['librato.svg'],
  'Lift': ['liftweb.svg'],
  'lighttpd': ['lighttpd.svg'],
  'LinkedIn': ['linkedin.svg'],
  'linkerd': ['linkerd.svg'],
  'Linode': ['linode.svg'],
  'Linux Mint': ['linux-mint.svg'],
  'Litmus': ['litmus.svg'],
  'loader': ['loader.svg'],
  'Locent': ['locent.svg'],
  'Lodash': ['lodash.svg'],
  'logentries': ['logentries.svg'],
  'loggly': ['loggly.svg'],
  'Looker': ['looker.svg'],
  'Lookback': ['lookback.svg'],
  'Loopback': ['loopback.svg'],
  'Losant': ['losant.svg'],
  'Lotus': ['lotus.svg'],
  'Lua': ['lua.svg'],
  'Lucene': ['lucene.svg'],
  'Lucene.net': ['lucene.net.svg'],
  'Lumen': ['lumen.svg'],
  'lynda.com': ['lynda.svg'],
  'Mac OS X': ['macosx.svg'],
  'mageia': ['mageia.svg'],
  'Magento': ['magento.svg'],
  'Magneto': ['magneto.svg'],
  'Mailchimp': ['mailchimp-freddie.svg', 'mailchimp.svg'],
  'MailDeveloper': ['maildeveloper.svg'],
  'Mailgun': ['mailgun.svg'],
  'Mandrill': ['mandrill-shield.svg', 'mandrill.svg'],
  'manifoldJS': ['manifoldjs.svg'],
  'Mantl': ['mantl.svg'],
  'MAPS.ME': ['maps-me.svg'],
  'Mapzen': ['mapzen.svg'],
  'MariaDB': ['mariadb.svg'],
  'Marionette.js': ['marionette.svg'],
  'Markdown': ['markdown.svg'],
  'Marvel': ['marvel.svg'],
  'Mattermost': ['mattermost.svg'],
  'MaxCDN': ['maxcdn.svg'],
  'Material UI': ['material-ui.svg'],
  'MDN': ['mdn.svg'],
  'Mean': ['meanio.svg'],
  'Medium': ['medium.svg'],
  'Memcached': ['memcached.svg'],
  'MemSQL': ['memsql.svg'],
  'mention': ['mention.svg'],
  'Mercurial': ['mercurial.svg'],
  'Mern': ['mern.svg'],
  'Mesos': ['mesos.svg'],
  'Mesosphere': ['mesosphere.svg'],
  'Metabase': ['metabase.svg'],
  'Meteor': ['meteor-icon.svg', 'meteor.svg'],
  'Microsoft': ['microsoft.svg'],
  'Microsoft Edge': ['microsoft-edge.svg'],
  'Middleman': ['middleman.svg'],
  'Mithril': ['mithril.svg'],
  'Mixmax': ['mixmax.svg'],
  'Mixpanel': ['mixpanel.svg'],
  'MobX': ['mobx.svg'],
  'Mocha': ['mocha.svg'],
  'Mockflow': ['mockflow.svg'],
  'Modernizr': ['modernizr.svg'],
  'Modulus': ['modulus.svg'],
  'MODX': ['modx.svg'],
  'Moment.js': ['momentjs.svg'],
  'MooTools': ['mootools.svg'],
  'MongoDB': ['mongodb.svg'],
  'MongoLab': ['mongolab.svg'],
  'Monero': ['monero.svg'],
  'Mono': ['mono.svg'],
  'Mozilla': ['mozilla.svg'],
  'MySQL': ['mysql.svg'],
  'Myth': ['myth.svg'],
  'Namecheap': ['namecheap.svg'],
  'NativeScript': ['nativescript.svg'],
  'Neat': ['neat.svg'],
  'Neo4j': ['neo4j.svg'],
  'Neonmetrics': ['neonmetrics.svg'],
  'Neovim': ['neovim.svg'],
  'Netbeans': ['netbeans.svg'],
  'Netlify': ['netlify.svg'],
  'Netuitive': ['netuitive.svg'],
  'New Relic': ['new-relic.svg'],
  'NGINX': ['nginx.svg'],
  'Nightwatch.js': ['nightwatch.svg'],
  'Nodal': ['nodal.svg'],
  'Nodejitsu': ['nodejitsu.svg'],
  'Node.js': ['nodejs-icon.svg', 'nodejs.svg'],
  'NodeBots': ['nodebots.svg'],
  'nodemon': ['nodemon.svg'],
  'Node-Sass': ['node-sass.svg'],
  'Noysi': ['noysi.svg'],
  'Nomad': ['nomad.svg'],
  'NPM': ['npm.svg', 'npm-2.svg'],
  'Nuclide': ['nuclide.svg'],
  'NuoDB': ['nuodb.svg'],
  'NW.js a.k.a. Nodewebkit': ['nodewebkit.svg'],
  'O\'Reilly': ['oreilly.svg'],
  'OAuth': ['oauth.svg'],
  'OCaml': ['ocaml.svg'],
  'olapic': ['olapic.svg'],
  'Olark': ['olark.svg'],
  'OneSignal': ['onesignal.svg'],
  'opbeat': ['opbeat.svg'],
  'Open Graph': ['open-graph.svg'],
  'Open Source Hardware Association': ['oshw.svg'],
  'Open Source Initiative': ['opensource.svg'],
  'OpenCart': ['opencart.svg'],
  'OpenLayers': ['openlayers.svg'],
  'OpenShift': ['openshift.svg'],
  'openstack': ['openstack.svg'],
  'Opera': ['opera.svg'],
  'OpsGenie': ['opsgenie.svg'],
  'Opsmatic': ['opsmatic.svg'],
  'Opsee': ['opsee.svg'],
  'Optimizely': ['optimizely.svg'],
  'Oracle': ['oracle.svg'],
  'Origami': ['origami.svg'],
  'osquery': ['osquery.svg'],
  'Otto': ['otto.svg'],
  'pagekite': ['pagekite.svg'],
  'Panda': ['panda.svg'],
  'Parse': ['parse.svg'],
  'parsehub': ['parsehub.svg'],
  'Passbolt': ['passbolt.svg'],
  'Passport': ['passport.svg'],
  'Patreon': ['patreon.svg'],
  'PayPal': ['paypal.svg'],
  'Pepperoni': ['pepperoni.svg'],
  'Percona': ['percona.svg'],
  'Percy': ['percy.svg'],
  'Perf Rocks': ['perf-rocks.svg'],
  'Periscope': ['periscope.svg'],
  'Perl': ['perl.svg'],
  'Phalcon': ['phalcon.svg'],
  'Phoenix': ['phoenix.svg'],
  'PhoneGap': ['phonegap.svg', 'phonegap-bot.svg'],
  'PHP': ['php.svg'],
  'PhpStorm': ['phpstorm.svg'],
  'Picasa': ['picasa.svg'],
  'Pingdom': ['pingdom.svg'],
  'Pinterest': ['pinterest.svg'],
  'pipedrive': ['pipedrive.svg'],
  'Pivotal Tracker': ['pivotal_tracker.svg'],
  'Pixate': ['pixate.svg'],
  'Pixelapse': ['pixelapse.svg'],
  'Plastic SCM': ['plastic-scm.svg'],
  'PlatformIO': ['platformio.svg'],
  'Play': ['play.svg'],
  'PM2': ['pm2.svg'],
  'Podio': ['podio.svg'],
  'Polymer': ['polymer.svg'],
  'Positionly': ['positionly.svg'],
  'PostCSS': ['postcss.svg'],
  'PostgreSQL': ['postgresql.svg'],
  'PouchDB': ['pouchdb.svg'],
  'Preact': ['preact.svg'],
  'Precursor': ['precursor.svg'],
  'PrestaShop': ['prestashop.svg'],
  'Presto': ['presto.svg'],
  'ProcessWire': ['processwire-icon.svg', 'processwire.svg'],
  'Product Hunt': ['producthunt.svg'],
  'ProductBoard': ['productboard.svg'],
  'Producteev': ['producteev.svg'],
  'Prometheus': ['prometheus.svg'],
  'Promises/A+': ['promises.svg'],
  'Prospect': ['prospect.svg'],
  'Protactor': ['protactor.svg'],
  'Prott': ['prott.svg'],
  'Proto.io': ['protoio.svg'],
  'Protonet': ['protonet.svg'],
  'Pug': ['pug.svg'],
  'Puppet': ['puppet.svg'],
  'Puppy Linux': ['puppy-linux.svg'],
  'Pushbullet': ['pushbullet.svg'],
  'Pusher': ['pusher.svg'],
  'PyCharm': ['pycharm.svg'],
  'Python': ['python.svg'],
  'Pyup': ['pyup.svg'],
  'Q': ['q.svg'],
  'Qordoba': ['qordoba.svg'],
  'Quay': ['quay.svg'],
  'quobyte': ['quobyte.svg'],
  'Quora': ['quora.svg'],
  'Qt': ['qt.svg'],
  'R': ['r-lang.svg'],
  'RabbitMQ': ['rabbitmq.svg'],
  'Rackspace': ['rackspace.svg'],
  'Rails': ['rails.svg'],
  'Ramda': ['ramda.svg'],
  'RAML': ['raml.svg'],
  'Rancher': ['rancher.svg'],
  'randomColor': ['randomcolor.svg'],
  'Raphaël': ['raphael.svg'],
  'Raspberry Pi': ['raspberry-pi.svg'],
  'React': ['react.svg'],
  'React/Router': ['react-router.svg'],
  'ReactiveX': ['reactivex.svg'],
  'Reapp': ['reapp.svg'],
  'Reddit': ['reddit.svg'],
  'RedHat': ['redhat.svg'],
  'Redis': ['redis.svg'],
  'Redsmin': ['redsmin.svg'],
  'Redspread': ['redspread.svg'],
  'Redux': ['redux.svg'],
  'Refactor.io': ['refactor.svg'],
  'Reindex': ['reindex.svg'],
  'Relay': ['relay.svg'],
  'Remergr': ['remergr.svg'],
  'RequireJS': ['require.svg'],
  'Rest': ['rest.svg'],
  'rest.li': ['rest-li.svg'],
  'RethinkDB': ['rethinkdb.svg'],
  'Riak': ['riak.svg'],
  'Riot': ['riot.svg'],
  'rkt': ['rkt.svg'],
  'RocksDB': ['rocksdb.svg'],
  'Rollbar': ['rollbar.svg'],
  'Rollup.js': ['rollupjs.svg'],
  'RocketChat': ['rocket-chat.svg'],
  'RSA': ['rsa.svg'],
  'RSMQ': ['rsmq.svg'],
  'RuboCop': ['rubocop.svg'],
  'Ruby': ['ruby.svg'],
  'RubyGems': ['rubygems.svg'],
  'RubyMine': ['rubymine.svg'],
  'Runnable': ['runnable.svg'],
  'RunAbove': ['run-above.svg'],
  'Rum': ['rum.svg'],
  'runscope': ['runscope.svg'],
  'Rust': ['rust.svg'],
  'Safari': ['safari.svg'],
  'Sails': ['sails.svg'],
  'Salesforce': ['salesforce.svg'],
  'SaltStack': ['saltstack.svg'],
  'Sameroom': ['sameroom.svg'],
  'Sass': ['sass.svg'],
  'SassDoc': ['sass-doc.svg'],
  'Sauce Labs': ['saucelabs.svg'],
  'Scala': ['scala.svg'],
  'Scaphold': ['scaphold.svg'],
  'Scribd': ['scribd.svg'],
  'section.io': ['sectionio.svg'],
  'Sencha Touch': ['sencha.svg'],
  'Seneca': ['seneca.svg'],
  'Segment': ['segment.svg'],
  'Semantic UI': ['semantic-ui.svg'],
  'Semaphore': ['semaphore.svg'],
  'SendGrid': ['sendgrid.svg'],
  'sensu': ['sensu.svg'],
  'Sentry': ['sentry.svg'],
  'Sequelize': ['sequelize.svg'],
  'Serverless': ['serveless.svg'],
  'Sherlock': ['sherlock.svg'],
  'Shields.io': ['shields.svg'],
  'Shipit': ['shipit.svg'],
  'Shippable': ['shippable.svg'],
  'Shogun': ['shogun.svg'],
  'Shopify': ['shopify.svg'],
  'Sidekick': ['sidekick.svg'],
  'Sidekiq': ['sidekiq.svg'],
  'Sinatra': ['sinatra.svg'],
  'Siphon': ['siphon.svg'],
  'SitePoint': ['sitepoint.svg'],
  'Sketch': ['sketchapp.svg'],
  'Skylight': ['skylight.svg'],
  'Skype': ['skype.svg'],
  'slack': ['slack.svg'],
  'slides': ['slides.svg'],
  'Slim': ['slim.svg'],
  'Smashing Magazine': ['smashingmagazine.svg'],
  'Snap.svg': ['snap-svg.svg'],
  'Snupps': ['snupps.svg'],
  'Socket.io': ['socket.io.svg'],
  'Solr': ['solr.svg'],
  'soundcloud': ['soundcloud.svg'],
  'SourceTree': ['sourcetree.svg'],
  'Spark': ['spark.svg'],
  'Sparkcentral': ['sparkcentral.svg'],
  'SparkPost': ['sparkpost.svg'],
  'Speaker Deck': ['speakerdeck.svg'],
  'Spring': ['spring.svg'],
  'SQLdep': ['sqldep.svg'],
  'SQLite': ['sqlite.svg'],
  'Square': ['square.svg'],
  'Squarespace': ['squarespace.svg'],
  'Stack Overflow': ['stackoverflow.svg'],
  'stackshare': ['stackshare.svg'],
  'Stacksmith': ['stacksmith.svg'],
  'Stash': ['stash.svg'],
  'StatusPage': ['statuspage.svg'],
  'Steroids': ['steroids.svg'],
  'Stetho': ['stetho.svg'],
  'stickermule': ['stickermule.svg'],
  'StopLight': ['stoplight.svg'],
  'Stormpath': ['stormpath.svg'],
  'Strider': ['strider.svg'],
  'Stripe': ['stripe.svg'],
  'StrongLoop': ['strongloop.svg'],
  'Struts': ['struts.svg'],
  'StyleCI': ['styleci.svg'],
  'stylelint': ['stylelint.svg'],
  'Stylus': ['stylus.svg'],
  'Subversion': ['subversion.svg'],
  'Supergiant': ['supergiant.svg'],
  'Supersonic': ['supersonic.svg'],
  'supportkit': ['supportkit.svg'],
  'Surge': ['surge.svg'],
  'Suse': ['suse.svg'],
  'survicate': ['survicate.svg'],
  'Susy': ['susy.svg'],
  'SVG': ['svg.svg'],
  'Swift': ['swift.svg'],
  'Swiftype': ['swiftype.svg'],
  'Symfony': ['symfony.svg'],
  'Snyk': ['snyk.svg'],
  'Sysdig': ['sysdig.svg'],
  'T3': ['t3.svg'],
  'TargetProcess': ['targetprocess.svg'],
  'Taiga': ['taiga.svg'],
  'TasteJS': ['tastejs.svg'],
  'Teamgrid': ['teamgrid.svg'],
  'teamwork': ['teamwork.svg'],
  'Tecnotic': ['tectonic.svg'],
  'Terminal': ['terminal.svg'],
  'Terraform': ['terraform.svg'],
  'TestLodge': ['testlodge.svg'],
  'Testmunk': ['testmunk.svg'],
  'Thimble': ['thimble.svg'],
  'Titon': ['titon.svg'],
  'Todoist': ['todoist.svg'],
  'TodoMVC': ['todomvc.svg'],
  'Traackr': ['traackr.svg'],
  'Trac': ['trac.svg'],
  'Travis CI': ['travis-ci.svg'],
  'Treasure Data': ['treasuredata.svg'],
  'treehouse': ['treehouse.svg'],
  'Trello': ['trello.svg'],
  'tsū˜': ['tsu.svg'],
  'tsuru': ['tsuru.svg'],
  'tumblr': ['tumblr-icon.svg', 'tumblr.svg'],
  'TuneIn': ['tunein.svg'],
  'Turret': ['turret.svg'],
  'tuts+': ['tutsplus.svg'],
  'Tutum': ['tutum.svg'],
  'Tux': ['tux.svg'],
  'Twilio': ['twilio.svg'],
  'Twitch': ['twitch.svg'],
  'Twitter': ['twitter.svg'],
  'Typeform': ['typeform.svg'],
  'ubuntu': ['ubuntu.svg'],
  'Udemy': ['udemy.svg'],
  'uikit': ['uikit.svg'],
  'Unbounce': ['unbounce.svg'],
  'Undertow': ['undertow.svg'],
  'UnitJS': ['unitjs.svg'],
  'Unity': ['unity.svg'],
  'Upcase': ['upcase.svg'],
  'Upwork': ['upwork.svg'],
  'UserTesting': ['user-testing.svg'],
  'uservoice': ['uservoice.svg'],
  'V8': ['v8.svg'],
  'Vaadin': ['vaadin.svg'],
  'VAddy': ['vaddy.svg'],
  'Vagrant': ['vagrant.svg'],
  'Vault': ['vault.svg'],
  'VerneMQ': ['vernemq.svg'],
  'VictorOps': ['victorops.svg'],
  'Vim': ['vim.svg'],
  'Vimeo': ['vimeo-icon.svg', 'vimeo.svg'],
  'Vine': ['vine.svg'],
  'Visual Studio': ['visual-studio.svg'],
  'Visual Website Optimizer': ['visual_website_optimizer.svg'],
  'Vivaldi': ['vivaldi.svg'],
  'Void': ['void.svg'],
  'Vue.js': ['vue.svg'],
  'Xamarin': ['xamarin.svg'],
  'W3C': ['w3c.svg'],
  'WakaTime': ['wakatime.svg'],
  'Waffle': ['waffle.svg'],
  'Wagtail': ['wagtail.svg'],
  'Weave': ['weave.svg'],
  'WebComponents': ['webcomponents.svg'],
  'webhooks': ['webhooks.svg'],
  'webpack': ['webpack.svg'],
  'WebPlatform': ['webplatform.svg'],
  'WebRTC': ['webrtc.svg'],
  'WebSocket': ['websocket.svg'],
  'WebStorm': ['webstorm.svg'],
  'WebTorrent': ['webtorrent.svg'],
  'Weebly': ['weebly.svg'],
  'Wercker': ['wercker.svg'],
  'WHATWG': ['whatwg.svg'],
  'Wi-Fi': ['wifi.svg'],
  'Wicket': ['wicket.svg'],
  'Windows': ['microsoft-windows.svg'],
  'WiredTree': ['wiredtree.svg'],
  'Wix': ['wix.svg'],
  'WooCommerce': ['woocommerce.svg'],
  'Woopra': ['woopra.svg'],
  'Wordpress': ['wordpress-icon.svg', 'wordpress.svg'],
  'Workboard': ['workboard.svg'],
  'WP engine': ['wpengine.svg'],
  'Wufoo': ['wufoo.svg'],
  'X-Ray Goggles': ['x-ray-goggles.svg'],
  'XAMPP': ['xampp.svg'],
  'Xero': ['xero.svg'],
  'Xplenty': ['xplenty.svg'],
  'Xtend': ['xtend.svg'],
  'XWiki': ['xwiki.svg'],
  'Yahoo!': ['yahoo.svg'],
  'YCombinator': ['ycombinator.svg'],
  'Yeoman': ['yeoman.svg'],
  'Yii': ['yii.svg'],
  'Yammer': ['yammer.svg'],
  'Yandex': ['yandex-ru.svg'],
  'YouTrack': ['youtrack.svg'],
  'YouTube': ['youtube.svg'],
  'Zapier': ['zapier.svg'],
  'Zend Framework': ['zend-framework.svg'],
  'Zendesk': ['zendesk.svg'],
  'Zenhub': ['zenhub.svg'],
  'Zest': ['zest.svg'],
  'ZigBee': ['zigbee.svg'],
  'Zoho': ['zoho.svg'],
  'Zube': ['zube.svg'],
  'Zulip': ['zulip.svg'],
  'Z-Wave': ['zwave.svg'],
};
